import './globals.css'
import { Inter } from 'next/font/google'
import { CartProvider } from '@/context/Store';
import Minicart from './components/Minicart';
import SearchBar from './components/SearchBar';
import Link from 'next/link';
import Messages from './components/Messages';
import Nav from './components/Nav'
import {CustomerProvider} from '@/hooks/useCustomer'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CustomerProvider>
        <CartProvider>    
          <body className={inter.className}>
            <nav className='fixed w-full bg-gray-900 text-white top-0 z-50'>
              <div className='flex items-center justify-between mx-auto max-w-6xl px-6 py-4'>             
                <Nav />
                <SearchBar />
                <Minicart />
              </div>
            </nav>
            <div>
              <Messages />
            </div>
            {children}
          </body>
        </CartProvider>
      </CustomerProvider>
    </html>
  )
}
